name: Flutter format and lint

on:
  pull_request:
    branches:
      - "**"

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
      - run: which flutter

      - name: flutter format check
        run: dart format -o none --set-exit-if-changed .
